"""Deterministic explanation generation.

Explanations are assembled from the evidence that was actually stored during
scoring. Nothing is generated by a language model and no claim is made that is
not backed by a snippet taken from the resume itself. Absent evidence is always
phrased as "no evidence was found in the submitted resume" rather than as a
statement about the person.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.config import (
    COMPONENT_LABELS,
    COMPONENT_ORDER,
    EXPLANATION_DETAILED_TOP_N,
    MAX_SEMANTIC_ITEMS_IN_EXPLANATION,
    MAX_SKILLS_IN_EXPLANATION,
)
from app.services.category_scorer import CandidateScores, ScoringPlan
from app.services.jd_analyzer import JobRequirements


def _join(names: list[str], limit: int = MAX_SKILLS_IN_EXPLANATION) -> str:
    if not names:
        return ""
    shown = names[:limit]
    remainder = len(names) - len(shown)
    text = ", ".join(shown)
    if remainder > 0:
        text += f" and {remainder} more"
    return text


def _not_found_phrase(names: list[str]) -> str:
    if not names:
        return ""
    listed = _join(names)
    verb = "was" if len(names[:MAX_SKILLS_IN_EXPLANATION]) == 1 else "were"
    return f"No evidence of {listed} {verb} found in the submitted resume."


def generate_explanation(
    *,
    rank: int,
    candidate_label: str,
    scores: CandidateScores,
    job: JobRequirements,
    plan: ScoringPlan,
) -> str:
    """Build the candidate explanation paragraph."""
    detailed = rank <= EXPLANATION_DETAILED_TOP_N
    parts: list[str] = [
        f"Ranked {rank} with a final score of {scores.final_score:.1f} out of 100."
    ]

    matched_required = [item.name for item in scores.matched_required_skills]
    if job.required_skills:
        parts.append(
            f"Matched {len(matched_required)} of {len(job.required_skills)} required "
            f"skills ({scores.component_scores['required_skills']:.1f}/100)"
            + (f": {_join(matched_required)}." if matched_required else ".")
        )

    if detailed:
        matched_other = [item.name for item in scores.matched_other_keywords]
        if job.other_keywords:
            parts.append(
                f"Other relevant keywords matched {len(matched_other)} of "
                f"{len(job.other_keywords)}"
                + (f": {_join(matched_other)}." if matched_other else ".")
            )

        supported = [item for item in scores.semantic_evidence if item.meets_threshold]
        top_semantic = sorted(supported, key=lambda item: item.similarity, reverse=True)[
            :MAX_SEMANTIC_ITEMS_IN_EXPLANATION
        ]
        if top_semantic:
            parts.append(
                f"Semantic requirement matching scored "
                f"{scores.component_scores['semantic_match']:.1f}/100 with "
                f"{len(supported)} of {len(scores.semantic_evidence)} requirement "
                "statements supported by resume evidence. Strongest alignment: "
                + "; ".join(
                    f'requirement "{item.requirement}" supported by "{item.best_evidence}" '
                    f"(similarity {item.similarity:.2f})"
                    for item in top_semantic
                )
                + "."
            )
        else:
            parts.append(
                f"Semantic requirement matching scored "
                f"{scores.component_scores['semantic_match']:.1f}/100; no resume passage "
                "reached the evidence threshold for the stated requirements."
            )

        if scores.project_experience_evidence:
            best = scores.project_experience_evidence[0]
            parts.append(
                "Project and experience relevance scored "
                f"{scores.component_scores['project_experience']:.1f}/100, supported by "
                f'"{best.best_evidence}" (similarity {best.similarity:.2f}).'
            )
        elif "project_experience" in plan.effective_weights:
            parts.append(
                "Project and experience relevance scored "
                f"{scores.component_scores['project_experience']:.1f}/100; no project or "
                "employment passage reached the evidence threshold."
            )

        if job.education_requirements:
            if scores.education_evidence:
                item = scores.education_evidence[0]
                parts.append(
                    f"Education requirement matched ({item.name}), evidenced by "
                    f'"{item.evidence}".'
                )
            else:
                parts.append(
                    "No evidence of the requested education was found in the "
                    "submitted resume."
                )

        if job.certification_requirements:
            if scores.certification_evidence:
                parts.append(
                    "Requested certifications found: "
                    + _join([item.name for item in scores.certification_evidence])
                    + "."
                )
            else:
                parts.append(
                    "No evidence of the requested certifications was found in the "
                    "submitted resume."
                )

        if job.soft_skills and scores.soft_skill_evidence:
            item = scores.soft_skill_evidence[0]
            parts.append(
                f"Soft-skill evidence for {item.name} is suggested by "
                f'"{item.evidence}" — a cautious signal only.'
            )

    if scores.required_skills_not_found:
        parts.append(_not_found_phrase(scores.required_skills_not_found))

    for penalty in scores.penalties:
        parts.append(
            f"Penalty applied: -{penalty.points:.1f} points. {penalty.detail}"
        )

    if detailed:
        top_contributions = sorted(
            scores.weighted_contributions.items(), key=lambda pair: pair[1], reverse=True
        )[:3]
        parts.append(
            "Largest contributions to the final score: "
            + ", ".join(
                f"{COMPONENT_LABELS[component]} {value:.1f} points"
                for component, value in top_contributions
            )
            + "."
        )

    if scores.used_section_fallback:
        parts.append(
            "No project or experience headings were detected, so the whole document "
            "was used for practical evidence. Formatting alone does not reduce the score."
        )

    return " ".join(parts)


# --------------------------------------------------------------------------- #
# Candidate comparison
# --------------------------------------------------------------------------- #
@dataclass
class ComponentDifference:
    component: str
    label: str
    candidate_a_score: float
    candidate_b_score: float
    difference: float
    effective_weight: float
    weighted_difference: float


@dataclass
class ComparisonResult:
    candidate_a_id: str
    candidate_b_id: str
    candidate_a_name: str
    candidate_b_name: str
    candidate_a_final_score: float
    candidate_b_final_score: float
    final_score_difference: float
    component_differences: list[ComponentDifference] = field(default_factory=list)
    only_a_required_skills: list[str] = field(default_factory=list)
    only_b_required_skills: list[str] = field(default_factory=list)
    shared_required_skills: list[str] = field(default_factory=list)
    only_a_other_keywords: list[str] = field(default_factory=list)
    only_b_other_keywords: list[str] = field(default_factory=list)
    a_requirements_not_found: list[str] = field(default_factory=list)
    b_requirements_not_found: list[str] = field(default_factory=list)
    a_best_evidence: list[str] = field(default_factory=list)
    b_best_evidence: list[str] = field(default_factory=list)
    explanation: str = ""


def _best_evidence_lines(scores: CandidateScores, limit: int = 3) -> list[str]:
    supported = sorted(
        [item for item in scores.semantic_evidence if item.meets_threshold],
        key=lambda item: item.similarity,
        reverse=True,
    )[:limit]
    return [
        f'"{item.requirement}" → "{item.best_evidence}" (similarity {item.similarity:.2f})'
        for item in supported
    ]


def compare_candidates(
    *,
    a_id: str,
    a_name: str,
    a_scores: CandidateScores,
    b_id: str,
    b_name: str,
    b_scores: CandidateScores,
    plan: ScoringPlan,
) -> ComparisonResult:
    """Explain the ranking order between two candidates from real differences."""
    differences: list[ComponentDifference] = []
    for component in COMPONENT_ORDER:
        weight = plan.effective_weights.get(component, 0.0)
        a_value = a_scores.component_scores.get(component, 0.0)
        b_value = b_scores.component_scores.get(component, 0.0)
        differences.append(
            ComponentDifference(
                component=component,
                label=COMPONENT_LABELS[component],
                candidate_a_score=a_value,
                candidate_b_score=b_value,
                difference=round(a_value - b_value, 2),
                effective_weight=round(weight, 4),
                weighted_difference=round((a_value - b_value) * weight, 3),
            )
        )

    a_required = {item.name for item in a_scores.matched_required_skills}
    b_required = {item.name for item in b_scores.matched_required_skills}
    a_other = {item.name for item in a_scores.matched_other_keywords}
    b_other = {item.name for item in b_scores.matched_other_keywords}

    result = ComparisonResult(
        candidate_a_id=a_id,
        candidate_b_id=b_id,
        candidate_a_name=a_name,
        candidate_b_name=b_name,
        candidate_a_final_score=a_scores.final_score,
        candidate_b_final_score=b_scores.final_score,
        final_score_difference=round(a_scores.final_score - b_scores.final_score, 2),
        component_differences=differences,
        only_a_required_skills=sorted(a_required - b_required),
        only_b_required_skills=sorted(b_required - a_required),
        shared_required_skills=sorted(a_required & b_required),
        only_a_other_keywords=sorted(a_other - b_other),
        only_b_other_keywords=sorted(b_other - a_other),
        a_requirements_not_found=list(a_scores.required_skills_not_found),
        b_requirements_not_found=list(b_scores.required_skills_not_found),
        a_best_evidence=_best_evidence_lines(a_scores),
        b_best_evidence=_best_evidence_lines(b_scores),
    )

    leader, trailer = (a_name, b_name)
    gap = result.final_score_difference
    if gap == 0:
        opening = (
            f"{a_name} and {b_name} have the same final score "
            f"({a_scores.final_score:.1f}). Tie-breaking then compares required-skill "
            "score, semantic score, project and experience score, and finally the "
            "candidate identifier."
        )
    else:
        if gap < 0:
            leader, trailer = b_name, a_name
        opening = (
            f"{leader} ranks above {trailer} by {abs(gap):.1f} points "
            f"({max(a_scores.final_score, b_scores.final_score):.1f} versus "
            f"{min(a_scores.final_score, b_scores.final_score):.1f})."
        )

    drivers = sorted(
        differences, key=lambda item: abs(item.weighted_difference), reverse=True
    )[:3]
    driver_sentences = []
    for item in drivers:
        if abs(item.weighted_difference) < 0.05:
            continue
        ahead, behind = (a_name, b_name) if item.difference > 0 else (b_name, a_name)
        driver_sentences.append(
            f"{item.label}: {ahead} scores {max(item.candidate_a_score, item.candidate_b_score):.1f} "
            f"versus {min(item.candidate_a_score, item.candidate_b_score):.1f} for {behind}, "
            f"worth {abs(item.weighted_difference):.1f} points at the effective weight of "
            f"{item.effective_weight:.0%}"
        )

    parts = [opening]
    if driver_sentences:
        parts.append("The difference comes mainly from — " + "; ".join(driver_sentences) + ".")

    if result.only_a_required_skills:
        parts.append(
            f"Required skills evidenced only in {a_name}'s resume: "
            f"{_join(result.only_a_required_skills)}."
        )
    if result.only_b_required_skills:
        parts.append(
            f"Required skills evidenced only in {b_name}'s resume: "
            f"{_join(result.only_b_required_skills)}."
        )
    if result.a_requirements_not_found:
        parts.append(
            f"For {a_name}: " + _not_found_phrase(result.a_requirements_not_found)
        )
    if result.b_requirements_not_found:
        parts.append(
            f"For {b_name}: " + _not_found_phrase(result.b_requirements_not_found)
        )

    parts.append(
        "This is a relevance comparison against the stated requirements, not a "
        "hiring recommendation."
    )
    result.explanation = " ".join(parts)
    return result
